### ISSUE TITLE
How can I suppress a check?

### ISSUE THREAD

**Issue by volodya-lombrozo** [l3r8yJ/oop-cop#105]
I've got one of the following messages:
```
Class 'RuleLineHitter' has bad naming, class ends with '-er' suffix
```
Suppose In general I want to use this check, however in some cases (like this one, I presented above) I want to have an ability to disable the check. Like the following:
```java
@SuppressWarnings("OOP.ErSuffix")
public final class RuleLineHitter implements Rule {
}
```
Do you have something like this?

**Comment by zoeself** [comment]
@volodya-lombrozo thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Could you help here, please?

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-01-09T14:00:13.924364``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by l3r8yJ** [comment]
@volodya-lombrozo this is still in development, I'll let you know when we add this suppression see #38

**Comment by l3r8yJ** [comment]
@volodya-lombrozo released, now it's `@SuppressWarnings("OOP.ErSuffixCheck")`, plugin version `0.2.6`, more info in readme

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
