### ISSUE TITLE
rename `maxClassNameLen` to `LongClassNameCheck`

### ISSUE THREAD

**Issue by h1alexbel** [l3r8yJ/oop-cop#111]
how about renaming `maxClassNameLen` maven plugin parameter to `LongClassNameCheck`?

I have idea of printing the name of the check that was failed:
```text
blah blah blah... (LongClassNameCheck)
```

@l3r8yJ what do you think?

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-01-13T07:10:04.380653``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by l3r8yJ** [comment]
@h1alexbel `LongClassNameCheck` contains `check` and i'm not sure that we need to assign some value to `check`

**Comment by h1alexbel** [comment]
@l3r8yJ yeah, that's a reasonable point

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
