### ISSUE TITLE
ErSuffixCheck.java:38-41: Implement Linked decorator for...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/oop-cop#117]
The puzzle `38-7c44aa58` from #38 has to be resolved: 

https://github.com/l3r8yJ/oop-cop/blob/d6d5c6226af5e455a39d9f59063d1a152549189e/src/main/java/ru/l3r8y/rule/ErSuffixCheck.java#L38-L41

The puzzle was created by @h1alexbel on 03-Jan-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-01-13T15:30:29.270344``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2024-01-13T15:30:29). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
