### ISSUE TITLE
ClassNames.java: Fetch check names from rule/*... 

### ISSUE THREAD

**Issue by zoeself** [l3r8yJ/oop-cop#138]
The puzzle ``-1161028634`` originating from #85 has to be resolved:

https://github.com/l3r8yJ/oop-cop/blob/ad9069f57165c26de6a604eb722a4d69421715d7/src/main/java/ru/l3r8y/parser/ClassNames.java#L68-L72

"Fetch check names from rule/* package (or check/*). Instead of hard-coding, we should fetch the ruleset from related package. Don't forget to remove this puzzle.".

The puzzle was created by h1alexbel at ``2024-01-10 11:27:04 +0300``. 
Estimation is ``90 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-02-22T21:20:03.752495``.

Estimation here is ``90 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by l3r8yJ** [comment]
@rultor release, tag is `0.2.7`
