### ISSUE TITLE
ErNamedClass.java:35-38: Annotations to skip rule. It is...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/oop-cop#38]
The puzzle `35-ba2ad0f0` from #35 has to be resolved: 

https://github.com/l3r8yJ/oop-cop/blob/b6cabb725bb75b5c8b634a8a7324423484005b2c/src/main/java/ru/l3r8y/rule/ErNamedClass.java#L35-L38

The puzzle was created by @rultor on 07-Apr-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
blocker for #105

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#115](https://github.com/l3r8yJ/oop-cop/issues/115), [#116](https://github.com/l3r8yJ/oop-cop/issues/116), [#117](https://github.com/l3r8yJ/oop-cop/issues/117) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#115](https://github.com/l3r8yJ/oop-cop/issues/115), [#117](https://github.com/l3r8yJ/oop-cop/issues/117) are still not solved; solved: [#116](https://github.com/l3r8yJ/oop-cop/issues/116).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#115](https://github.com/l3r8yJ/oop-cop/issues/115) is still not solved; solved: [#116](https://github.com/l3r8yJ/oop-cop/issues/116), [#117](https://github.com/l3r8yJ/oop-cop/issues/117).
